# dependabot.yaml reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        - patterns: "*"

  # jupyterlab extension
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      # one big pull request
      lab-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      # group major bumps
      lab-major:
        patterns:
          - "*"
        update-types:
          - major
