language: python
dist: trusty
sudo: required

notifications:
  email: false

services:
  - docker
matrix:
  include:
    - python: "2.7"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=sge
    - python: "3.6"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=sge
    - python: "2.7"
      env:
        - OS=ubuntu-14.04
        # JOBQUEUE=none is for tests that do not need a cluster to run
        - JOBQUEUE=none
    - python: "3.6"
      env:
        - OS=ubuntu-14.04
        # JOBQUEUE=none is for tests that do not need a cluster to run
        - JOBQUEUE=none
    - python: "3.6"
      env:
        - OS=ubuntu-14.04
        - JOBQUEUE=pbs
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - pwd
  # Init jobqueue environment: load init and test methods
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
install:
  - jobqueue_install
script:
  - jobqueue_script
after_success:
  - jobqueue_after_success

  # TODO
  # - pip install --no-cache-dir coveralls
  # - coveralls
