version: "3.4"

services:

  master:
    image: daskdev/dask-jobqueue:sge
    build:
      context: .
      target: master
      args:
        PYTHON_VERSION: ${TRAVIS_PYTHON_VERSION:-3.6}
    container_name: sge_master
    hostname: sge_master
    #network_mode: host
    volumes:
      - ../..:/dask-jobqueue
    command: bash /run-master.sh

  slave-one:
    image: daskdev/dask-jobqueue:sge-slave
    build:
      context: .
      target: slave
      args:
        PYTHON_VERSION: ${TRAVIS_PYTHON_VERSION:-3.6}
    container_name: slave_one
    hostname: slave_one
    #network_mode: host
    volumes:
      - ../..:/dask-jobqueue
    command: bash /run-slave.sh
    links:
      - "master:sge_master"
    depends_on:
      - master

  slave-two:
    image: daskdev/dask-jobqueue:sge-slave
    build:
      context: .
      target: slave
      args:
        PYTHON_VERSION: ${TRAVIS_PYTHON_VERSION:-3.6}
    container_name: slave_two
    hostname: slave_two
    #network_mode: host
    volumes:
      - ../..:/dask-jobqueue
    command: bash /run-slave.sh
    links:
      - "master:sge_master"
    depends_on:
      - master
